---

- name: apt update
  apt: update_cache=yes
  tags: php


- name: Install php-fpm and deps
  apt:
    state: present
    name:
      - php7.0
      - php7.0-cli
      - php7.0-fpm
      - php7.0-mysql
      - php7.0-json
      - php7.0-opcache
      - php7.0-mbstring
      - php7.0-xml
      - php7.0-gd
      - php7.0-curl
  notify: restart php
  tags: php
