---

- name: install mysql package
  apt:
    state: present
    name:
      - mysql-server
      - python-mysqldb
  tags: db

- name: create wordpress db
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
  tags: db
  notify: restart mysql

- name: create db user.
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_pwd }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: localhost
    state: present
  tags: db
