---
- name: test command
  shell: cat /etc/os-release
  tags: base

- name: set hostname
  hostname: name="{{ hostname }}"
  tags: base

- name: configure hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
  tags: base

- name: add multiverse repos
  apt_repository: repo='deb http://us.archive.ubuntu.com/ubuntu/ {{ ubuntu }} multiverse' state=present mode=0644
  tags: base

- name: add updates repo
  apt_repository: repo='deb http://us.archive.ubuntu.com/ubuntu/ {{ ubuntu }}-updates multiverse' state=present
  tags: base

- name: apt update
  apt: update_cache=yes
  tags: base

- name: apt upgrade
  apt: upgrade=yes
  tags: base

- name: install base packages
  apt:
    state: present
    name:
      - git
      - python3-pip
      - ntp
      - bc
      - unzip
      - clamav
      - nfs-common
  tags: base

- name: start service ntp, if not restarted
  service:
    name: ntp
    state: started
    enabled: yes
  tags: base

- name: create users
  user:
    state: present
    groups: sudo, adm
    shell: /bin/bash
    comment: sudo, adm
    name: "{{ item }}"
  with_items:
      - aiperichiltenalieva
  tags:
    - base
    - users

- name: add auth key to users
  authorized_key:
    state: present
    key: "{{ lookup('file', 'authorized_keys_' + item)  }}"
    user: "{{ item }}"
  with_items:
    - aiperichiltenalieva
  tags:
    - base
    - users

- name: add users to sudo
  lineinfile:
    dest: /etc/sudoers
    line: '%sudo ALL=(ALL) NOPASSWD:ALL'
  tags:
    - base
    - users

- name: download aws agent
  get_url:
    url: https://inspector-agent.amazonaws.com/linux/latest/install
    dest: /tmp/install-aws-inspector
    mode: 0755
  tags:
    - base
    - awsagent

- name: install aws inspector
  shell: /tmp/install-aws-inspector #creates=/etc/init.d/awsagent
  tags:
    - base
    - awsagent
