---

- name: apt update
  apt: update_cache=yes
  tags: zb


- name: Install apache httpd
  apt:
    state: present
    name:
      - apache2
      - libapache2-mod-php
  tags: zb


- name: install mysql package
  apt:
    state: present
    name:
      - mysql-server
      - python-mysqldb
  notify: restart mysql
  tags: zb

- name: Install php
  apt:
    state: present
    name:
      - php
      - php-mbstring
      - php-gd
      - php-xml
      - php-bcmath
      - php-ldap
      - php-mysql
  tags: zb

#tested and successfully changed--verified ubuntu@ip-172-31-59-154:/etc/php/7.0/apache2
# can be improved, hardcoded the php version.
- name: Set date timezone for America or Chicago
  become: true
  lineinfile:
    dest: /etc/php/7.0/apache2/php.ini
    regexp: "date.timezone ="
    line: "date.timezone = America/Chicago"
  tags: zb

- name: download zabbix
  get_url:
      url: https://repo.zabbix.com/zabbix/4.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.2-3%2Bbionic_all.deb
      dest: /zabbix
      mode: 0755
  tags: zb

- dpkg_selections:
    name: zabbix-release_4.2-3+bionic_all.deb
    selection: install
  tags: zb

- name: apt update
  become: true
  apt:
    update_cache: yes
  tags: zb

- name: Install zabbix
  apt:
    state: present
    name:
      - zabbix-server-mysql
      - zabbix-frontend-php
      - zabbix-agent
  tags: zb
